---

- block:

  - name: Distribute the client certs for workers nodes
    become: yes
    copy:
      src: "/tmp/masters/{{ groups.masters | first }}/var/lib/kubernetes/{{item}}"
      dest: /var/lib/kubernetes/
      owner: root
      group: root
      mode: '0644'
    loop:
      - ca.pem
      - ca-key.pem
      - admin.pem
      - admin-key.pem
      - kube-proxy-key.pem
      - kube-proxy.pem
      - admin.kubeconfig
      - kube-proxy.kubeconfig

  - name: Copy scripts in {{kubernetes_dir_certs}}
    become: yes
    template:
      src: gen_certs_worker_nodes.sh.j2
      mode: '0755'
      dest: "{{ kubernetes_dir_certs }}/gen_certs.sh"

  - name: Run a script using an executable in a system path
    become: yes
    shell: "{{ kubernetes_dir_certs }}/gen_certs.sh"
    args:
      chdir: "{{ kubernetes_dir_certs }}"